service: vm-scheduler
runtime: python27
api_version: 1
threadsafe: yes
instance_class: B2
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:

- url: /_services/.*
  script: main.app
  secure: always
  login: admin

- url: /_ah/start
  script: main.app
  secure: always

- url: /_ah/stop
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
