service: default
runtime: python27
api_version: 1
threadsafe: yes
instance_class: B2
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(robots\.txt|favicon\.ico)
- url: /static/css
  static_dir: static/css
- url: /static/js
  static_dir: static/js
- url: /static/images
  static_dir: static/images
- url: /static/fonts
  static_dir: static/fonts
- url: /_ah/start
  script: app.app
  secure: always
- url: /_ah/stop
  script: app.app
  secure: always
- url: /.*
  script: app.app
  secure: always
  login: admin

builtins:
- remote_api: on

libraries:
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"
- name: ssl
  version: "2.7.11"
- name: webapp2
  version: "2.5.2"
